services:
  - type: web
    name: sistema-notificacao
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PROD
        value: true
      - key: SQLITE_PATH
        value: /data/data.db
      - key: PORT
        value: 1000